export const header = {
  slogan: "",
  title: "",
  description: "ALGUNOS DE NUESTROS CLIENTES",
  buttonText: "",
  buttonLink: "",
};

export const items = [
  "Factorial",
  "Yaba",
  "Mailtrack",
  "Broseta",
  "DerechoCom",
  "Taxdown",
  "Deale",
  "PldSpace",
  "Keybotic",
  "MyInvestor",
  "Shakers",
  "Caballero",
  "MasterChef",
  "Cabiedes",
  "Incapto",
  "LegalPigeon",
  "Criptan",
  "Horizm",
  "Psonrie",
  "Pwc",
];
